import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildCockpit,comparable,estimate,recommendation} from './pricing.js';
const sold=[
 {item_id:'DEN-001',name:'Levis 501 W32',ledger_status:'SOLD',sale_price_arbitrage:150,sold_on:'2026-05-01'},
 {item_id:'DEN-002',name:'Levis 501 W33',ledger_status:'SOLD',sale_price_arbitrage:160,sold_on:'2026-05-10'},
 {item_id:'DEN-003',name:'Levis 501 W32',ledger_status:'SOLD',sale_price_arbitrage:155,sold_on:'2026-05-20'},
 {item_id:'DEN-004',name:'Levis 501 W31',ledger_status:'SOLD',sale_price_arbitrage:165,sold_on:'2026-06-01'},
 {item_id:'DEN-005',name:'Levis 501 W32',ledger_status:'SOLD',sale_price_arbitrage:158,sold_on:'2026-06-10'},
 {item_id:'DEN-006',name:'Levis 501 W34',ledger_status:'SOLD',sale_price_arbitrage:152,sold_on:'2026-06-20'},
 {item_id:'DEN-007',name:'Lee 101 W32',ledger_status:'SOLD',sale_price_arbitrage:120,sold_on:'2026-06-25'},
 {item_id:'DEN-008',name:'Levis 501 W33',ledger_status:'SOLD',sale_price_arbitrage:162,sold_on:'2026-07-01'}
];
const live={item_id:'DEN-200',name:'Levis 501 W32',ledger_status:'LISTED-BACKLOG',vinted_item_id:'1',live_list_price:190,total_capital:40,listed_on:'2026-06-01'};
const dnaA={item_id:'DEN-201',name:'unhelpful import name',item_dna:{facts:{brand:"Levi's",model:'521',tagged_size:'W32 L32',wash:'mid blue',fit:'Relaxed Tapered',origin:'Polska',era:'1995',condition:'Very good'}}};
const dnaB={item_id:'DEN-202',name:'another imported name',item_dna:{facts:{brand:'LEVIS',model:'521',tagged_size:'W32 L32',wash:'MEDIUM BLUE',fit:'tapered',origin:'Poland',era:'1990s',condition:'BARDZO DOBRY'}}};
const dnaMatch=comparable(dnaA,dnaB);assert.ok(dnaMatch&&dnaMatch.reasons.includes('model 521'));assert.ok(dnaMatch.reasons.includes('wash'));assert.ok(dnaMatch.reasons.includes('fit'));assert.ok(dnaMatch.reasons.includes('origin'));assert.ok(dnaMatch.reasons.includes('era'));assert.ok(dnaMatch.reasons.includes('condition'));
const customCaseA={...dnaA,item_id:'DEN-203',item_dna:{facts:{...dnaA.item_dna.facts,fit:'Custom Curve',origin:'Australia'}}},customCaseB={...dnaB,item_id:'DEN-204',item_dna:{facts:{...dnaB.item_dna.facts,fit:'custom curve',origin:'AUSTRALIA'}}};const customCaseMatch=comparable(customCaseA,customCaseB);assert.ok(customCaseMatch.reasons.includes('fit'));assert.ok(customCaseMatch.reasons.includes('origin'));
const model=estimate(live,sold);assert.equal(model.status,'READY');assert.ok(model.center>=150&&model.center<=165);const nonDenim={item_id:'DEN-300',name:'Levis Wool Blazer Size M',ledger_status:'LISTED-BACKLOG',vinted_item_id:'2',live_list_price:190,total_capital:40,listed_on:'2026-06-01'};const cockpit=buildCockpit([...sold,live,nonDenim],[{vinted_item_id:'1',captured_at:'2026-06-01T10:00:00Z',price_pln:190,favourites:0,views:10},{vinted_item_id:'1',captured_at:'2026-07-13T10:00:00Z',price_pln:190,favourites:0,views:30}]);assert.equal(cockpit.rows.length,1);assert.equal(cockpit.rows[0].decision.action,'TEST_LOWER');assert.ok(cockpit.rows[0].decision.nextPrice>=live.total_capital);const stale=recommendation(live,model,{latest:{captured_at:'2026-06-01'},snapshotAge:4,price:190},{});assert.equal(stale.action,'OBSERVE');const protectedFloor=recommendation({...live,total_capital:188},model,{latest:{captured_at:'2026-07-12'},snapshotAge:0,price:190,daysLive:30,likesDelta:0},{});assert.equal(protectedFloor.action,'PRESENTATION');
const tooEarlyAbove=recommendation(live,model,{latest:{captured_at:'2026-07-12'},snapshotAge:0,price:190,daysLive:18,likes:0,likesDelta:0},{});assert.equal(tooEarlyAbove.action,'OBSERVE');assert.match(tooEarlyAbove.reason,/powyżej estymowanego zakresu/);
const underpriced=recommendation(live,model,{latest:{captured_at:'2026-07-12'},snapshotAge:0,price:100,daysLive:30,likes:4,likesDelta:3,historyDays:7},{});assert.equal(underpriced.action,'RAISE');assert.ok(underpriced.nextPrice>100);assert.match(underpriced.reason,/poniżej estymowanego zakresu/);console.log('Pricing cockpit tests passed');
const floatModel={status:'READY',low:65.19999999999999,high:243.8,center:180};const floatReason=recommendation(live,floatModel,{latest:{captured_at:'2026-07-12'},snapshotAge:0,price:260,daysLive:30,likes:0,likesDelta:0},{});assert.equal(floatReason.action,'TEST_LOWER');assert.match(floatReason.reason,/65 zł–244 zł/);assert.doesNotMatch(floatReason.reason,/65\.199999|243\.8/);const pricingHtml=readFileSync(new URL('./pricing.html',import.meta.url),'utf8');assert.match(pricingHtml,/RAISE:'Podnieś cenę'/);assert.match(pricingHtml,/RAISE:'raise'/);console.log('Pricing cockpit tests passed');
