import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const system=readFileSync(new URL('./system.html',import.meta.url),'utf8');
const operations=readFileSync(new URL('./operations.html',import.meta.url),'utf8');
assert.match(system,/Poczta Vinted/);
assert.match(system,/Ostatnia udana synchronizacja:/);
assert.match(system,/Połączenie OAuth jest potwierdzone/);
assert.match(system,/POŁĄCZONO — TRWA PIERWSZA SYNCHRONIZACJA/);
assert.match(system,/Odczytaj nowe maile/);
assert.match(system,/tylko maile nowsze od ostatniej udanej synchronizacji/);
assert.match(system,/Ostatnie zdarzenie biznesowe z Gmaila/);
assert.match(system,/run\.status==='SUCCEEDED'\?run\.finished_at:null/,'A fresh successful sync run must keep Gmail healthy even if the state row is delayed.');
assert.match(system,/gmail-action/,'The reconnect control must have its own spacing from status text.');
assert.match(system,/aktualnie otwarte/);
assert.match(system,/BŁĄD SYNCHRONIZACJI/);
assert.match(system,/WYMAGA PONOWNEGO POŁĄCZENIA/);
assert.match(operations,/Stan połączenia Gmail jest w System/);
assert.match(operations,/Kolejka transakcji/);
console.log('System Gmail health UX regression checks passed');
