import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const system=readFileSync(new URL('./system.html',import.meta.url),'utf8');
const operations=readFileSync(new URL('./operations.html',import.meta.url),'utf8');
const hq=readFileSync(new URL('./hq.js',import.meta.url),'utf8');
const relistMigration=readFileSync(new URL('../supabase/migrations/065_relist_pending_state_machine.sql',import.meta.url),'utf8');
const cacheMigration=readFileSync(new URL('../supabase/migrations/20260905110000_incremental_browser_snapshot_cache.sql',import.meta.url),'utf8');
assert.match(system,/Poczta Vinted/);
assert.match(system,/Ostatnia udana synchronizacja:/);
assert.match(system,/Połączenie OAuth jest potwierdzone/);
assert.match(system,/POŁĄCZONO — TRWA PIERWSZA SYNCHRONIZACJA/);
assert.match(system,/Odczytaj nowe maile/);
assert.match(system,/tylko maile nowsze od ostatniej udanej synchronizacji/);
assert.match(system,/Ostatnie zdarzenie biznesowe z Gmaila/);
assert.match(system,/run\.status==='SUCCEEDED'\?run\.finished_at:null/,'A fresh successful sync run must keep Gmail healthy even if the state row is delayed.');
assert.match(system,/gmail-action/,'The reconnect control must have its own spacing from status text.');
assert.match(system,/aktualnie otwarte/);
assert.match(system,/BŁĄD SYNCHRONIZACJI/);
assert.match(system,/WYMAGA PONOWNEGO POŁĄCZENIA/);
assert.match(operations,/Stan automatyzacji/);
assert.match(operations,/Kolejka transakcji/);
assert.match(operations,/RELIST PENDING/);
assert.match(operations,/relistCandidates/);
assert.match(relistMigration,/create table if not exists public\.hq_vinted_relist_candidates/);
assert.match(relistMigration,/actor = 'MANUAL' and current_new_count < 1/);
assert.match(relistMigration,/record_hq_relist_candidate/);
assert.match(hq,/const cacheKey='fadewell-hq-data-v6'/);
assert.doesNotMatch(hq,/JSON\.stringify\(value\)\.length>1500000/,'The browser cache must not silently stop growing at 1.5 MB.');
assert.match(hq,/async function refreshChangedData/,'The cache must refresh changed source collections without reloading all HQ data.');
assert.match(hq,/hq_listing_snapshots','hq_ledger_items','hq_review_queue','hq_ledger_events','hq_external_events/,'Every browser delta source must have an incremental route.');
assert.match(hq,/loadSnapshotCycles\(\)/,'Snapshot-only changes must refresh only current listing cycles.');
assert.match(hq,/sb\.rpc\('hq_browser_listing_cycles'\)/,'The browser must request bounded current snapshot cycles rather than a historical window.');
assert.match(cacheMigration,/hq_listing_snapshots_cloud_captured_at_index/);
assert.match(cacheMigration,/hq_browser_listing_cycles/);
console.log('System Gmail health UX regression checks passed');
