import assert from 'node:assert/strict';
import {buildTimeline} from './timeline.js';
const item={item_id:'DEN-900',vinted_item_id:'123',listing_url:'https://www.vinted.pl/items/123'};
const timeline=buildTimeline({item,ledgerEvents:[{id:7,event_type:'SALE',occurred_on:'2026-07-13',amount:140,detail:'Vinted Gmail sale notification',source:'VINTED',created_at:'2026-07-13T12:00:00Z'}],externalEvents:[{source_event_id:'mail-1',ledger_event_id:7,event_type:'SALE_PENDING',state:'AUTO_APPLIED',occurred_at:'2026-07-13T12:00:00Z'}],snapshots:[{vinted_item_id:'123',captured_at:'2026-07-10T09:00:00Z',title:'Test item',price_pln:179,favourites:4,views:10,visible:true,source:'github_actions_vinted'},{vinted_item_id:'123',captured_at:'2026-07-10T10:00:00Z',title:'Test item',price_pln:179,favourites:4,views:10,visible:true,source:'github_actions_vinted'},{vinted_item_id:'123',captured_at:'2026-07-13T09:00:00Z',title:'Test item',price_pln:159,favourites:7,views:13,visible:true,source:'github_actions_vinted'}]});
assert.equal(timeline.length,3,'unchanged snapshots must not create noise');assert.equal(timeline[0].title,'Sprzedano');assert.equal(timeline[0].evidence.filter(row=>row.label.startsWith('Gmail')).length,1,'Gmail proof must attach to the Ledger event, not duplicate it');assert.match(timeline.find(row=>row.title==='Zmiana zaobserwowana na Vinted').summary,/179 → 159 PLN/);assert.match(timeline.find(row=>row.title==='Zmiana zaobserwowana na Vinted').summary,/likes: 4 → 7/);
const review=buildTimeline({item,externalEvents:[{source_event_id:'mail-review',event_type:'SALE_PENDING',state:'NEEDS_REVIEW',item_title:'Unknown',amount:25,created_at:'2026-07-14T09:00:00Z'}]});assert.equal(review[0].type,'review');assert.match(review[0].summary,/wymaga przeglądu/);console.log('Truth timeline tests passed');
const listedItem={item_id:'DEN-237',name:'Levis 505 32/32 TR Nice Whiskering Cotton',live_title:'Levi’s 505 Regular Straight Zip Fly Jeans W32 L32'};
const listed=buildTimeline({item:listedItem,ledgerEvents:[{id:542,event_type:'LISTED',detail:'SYSTEM auto-resolver: score 106',source:'SYSTEM',created_at:'2026-08-20T14:02:53Z'}]});assert.match(listed[0].summary,/Tytuł w Ledger przed Vinted/);assert.match(listed[0].summary,/Levis 505 32\/32 TR Nice Whiskering Cotton/);
const invalidated=buildTimeline({item,ledgerEvents:[{id:543,event_type:'LISTED',detail:'wrong relist',source:'SYSTEM',created_at:'2026-08-20T14:02:54Z'},{id:544,event_type:'ADJUSTMENT',detail:'INVALIDATES_LEDGER_EVENT #543 · corrected',source:'MANUAL',created_at:'2026-08-20T14:10:00Z'}]});const old=invalidated.find(row=>row.id==='ledger:543');assert.equal(old.title,'Unieważnione automatyczne przypisanie');assert.match(old.summary,/nie jest już faktem bieżącym/);console.log('Title provenance and invalidation tests passed');
